---
# Ubuntu related OS tasks

- name: apt dist-upgrade
  apt:
    upgrade: dist
    autoremove: true

- name: install additional packages
  apt:
    name:
      - zip
      - unzip
      - bzip2
      - screen
      - curl
      - ffmpeg
      - imagemagick
      - ghostscript
      - libfile-fcntllock-perl
      - language-pack-en-base
      - software-properties-common
      - facter
      - nodejs 
    state: latest

- name: Install software from snap (with full access file system)
  snap:
    name:
      - atom
      - gitkraken
      - code
      - chromium
      - telegram-desktop
      - sublime-text
      - slack
      - skype
      - ruby
    classic: yes
